version: '2'

services:

  snow-removing:
    image: node:alpine
    container_name: 'snow-removing'
    hostname: 'snow-removing'
    working_dir: /usr/src/app
    volumes:
      - ./services/snow-removing:/usr/src/app
      - ./serviceAccountKey.json:/usr/src/app/serviceAccountKey.json
    command: yarn start

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - './data/mongo:/data/db'
    ports:
      - '27017:27017'
