version: '2'

services:

  kremen-snow-api:
    image: node:alpine
    container_name: 'kremen-snow-api'
    hostname: 'kremen-snow-api'
    working_dir: /usr/src/app
    volumes:
      - ./services/kremen-snow-api:/usr/src/app
    ports:
      - 22030:8080
    command: yarn start

  kremen-snow-parser:
    image: node:alpine
    container_name: 'kremen-snow-parser'
    hostname: 'kremen-snow-parser'
    working_dir: /usr/src/app
    volumes:
      - ./services/kremen-snow-parser:/usr/src/app
      - ./serviceAccountKey.json:/usr/src/app/serviceAccountKey.json
    command: yarn start

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - './data/mongo:/data/db'
    ports:
      - '27017:27017'
